/* Generated By:JavaCC: Do not edit this line. yal2jvmTreeConstants.java Version 4.1d1 */
public interface yal2jvmTreeConstants
{
  public int JJTPARSERBEGIN = 0;
  public int JJTVOID = 1;
  public int JJTMID = 2;
  public int JJTDECL = 3;
  public int JJTFUNC = 4;
  public int JJTDECLID = 5;
  public int JJTARRAYSIZE = 6;
  public int JJTADDSUBOP = 7;
  public int JJTINICVAR = 8;
  public int JJTFUNCID = 9;
  public int JJTISARRAY = 10;
  public int JJTASSIGNID = 11;
  public int JJTARGS = 12;
  public int JJTFUNCBODY = 13;
  public int JJTVARLISTID = 14;
  public int JJTARRAYID = 15;
  public int JJTSCALARELEMENT = 16;
  public int JJTSCALARID = 17;
  public int JJTSTMTLST = 18;
  public int JJTASSIGN = 19;
  public int JJTLHS = 20;
  public int JJTRHS = 21;
  public int JJTTERM = 22;
  public int JJTARITMOP = 23;
  public int JJTBITOP = 24;
  public int JJTARRSIZE = 25;
  public int JJTSCALAR = 26;
  public int JJTINTEGER = 27;
  public int JJTID = 28;
  public int JJTID2 = 29;
  public int JJTARGLIST = 30;
  public int JJTSIZE = 31;
  public int JJTEXPRTEST = 32;
  public int JJTWHILE = 33;
  public int JJTIF = 34;
  public int JJTCALLID = 35;
  public int JJTCALLID2 = 36;
  public int JJTARGUMENT = 37;
  public int JJTARGID = 38;
  public int JJTSTRING = 39;
  public int JJTARRAYINDEX = 40;
  public int JJTSCALARSIZE = 41;
  public int JJTINDEX = 42;
  public int JJTINDEXID = 43;


  public String[] jjtNodeName = {
    "parserBegin",
    "void",
    "MID",
    "Decl",
    "Func",
    "DeclID",
    "ArraySize",
    "AddSubOP",
    "InicVar",
    "FuncID",
    "IsArray",
    "AssignID",
    "Args",
    "FuncBody",
    "VarListID",
    "ArrayID",
    "ScalarElement",
    "ScalarID",
    "Stmtlst",
    "Assign",
    "Lhs",
    "Rhs",
    "Term",
    "AritmOP",
    "BitOP",
    "ArrSize",
    "Scalar",
    "INTEGER",
    "ID",
    "ID2",
    "ArgList",
    "Size",
    "Exprtest",
    "While",
    "If",
    "CallID",
    "CallID2",
    "Argument",
    "ArgID",
    "STRING",
    "ArrayIndex",
    "ScalarSize",
    "Index",
    "IndexID",
  };
}
/* JavaCC - OriginalChecksum=52ac91322d62dd752cc3f77511df956c (do not edit this line) */
