/* Generated By:JavaCC: Do not edit this line. yal2jvmTreeConstants.java Version 5.0 */
public interface yal2jvmTreeConstants
{
  public int JJTPARSERBEGIN = 0;
  public int JJTVOID = 1;
  public int JJTMID = 2;
  public int JJTDECL = 3;
  public int JJTFUNC = 4;
  public int JJTDECLID = 5;
  public int JJTARRAYSIZE = 6;
  public int JJTINICVAR = 7;
  public int JJTFUNCID = 8;
  public int JJTASSIGNID = 9;
  public int JJTARGS = 10;
  public int JJTFUNCBODY = 11;
  public int JJTVARLISTID = 12;
  public int JJTVARLISTID2 = 13;
  public int JJTARRAYID = 14;
  public int JJTSCALARELEMENT = 15;
  public int JJTSCALARID = 16;
  public int JJTSTMTLST = 17;
  public int JJTASSIGN = 18;
  public int JJTLHS = 19;
  public int JJTRHS = 20;
  public int JJTTERM = 21;
  public int JJTARITMOP = 22;
  public int JJTBITOP = 23;
  public int JJTADDSUBOP = 24;
  public int JJTTERM2 = 25;
  public int JJTARRSIZE = 26;
  public int JJTSCALAR = 27;
  public int JJTINTEGER = 28;
  public int JJTID = 29;
  public int JJTID2 = 30;
  public int JJTARGLIST = 31;
  public int JJTSIZE = 32;
  public int JJTEXPRTEST = 33;
  public int JJTWHILE = 34;
  public int JJTIF = 35;
  public int JJTCALLID = 36;
  public int JJTCALLID2 = 37;
  public int JJTARGUMENT = 38;
  public int JJTARGID = 39;
  public int JJTSTRING = 40;
  public int JJTARRAYINDEX = 41;
  public int JJTSCALARSIZE = 42;
  public int JJTINDEX = 43;
  public int JJTINDEXID = 44;


  public String[] jjtNodeName = {
    "parserBegin",
    "void",
    "MID",
    "Decl",
    "Func",
    "DeclID",
    "ArraySize",
    "InicVar",
    "FuncID",
    "AssignID",
    "Args",
    "FuncBody",
    "VarListID",
    "VarListID2",
    "ArrayID",
    "ScalarElement",
    "ScalarID",
    "Stmtlst",
    "Assign",
    "Lhs",
    "Rhs",
    "Term",
    "AritmOP",
    "BitOP",
    "AddSubOP",
    "Term2",
    "ArrSize",
    "Scalar",
    "INTEGER",
    "ID",
    "ID2",
    "ArgList",
    "Size",
    "Exprtest",
    "While",
    "If",
    "CallID",
    "CallID2",
    "Argument",
    "ArgID",
    "STRING",
    "ArrayIndex",
    "ScalarSize",
    "Index",
    "IndexID",
  };
}
/* JavaCC - OriginalChecksum=e3c534a8fa69e174d149d23c2f25f086 (do not edit this line) */
